name: prj-asa
services:
  site-01:
    build:
      context: .
      dockerfile: Dockerfile
    image: asa01
    ports:
      - '80:80'
    volumes:
      - ./site01:/user/share/nginx/html
    networks:
      - my-net


  site-02:
    build:
      context: .
      dockerfile: Dockerfile
    image: asa02
    ports:
      - '81:80'
    volumes:
      - ./site02:/user/share/nginx/html
    networks:
      - my-net

networks:
  my-net:
      driver: bridge