options {
    directory "/var/cache/bind";
    recursion yes;
    allow-query { any; };
    forwarders { 8.8.8.8; 8.8.4.4; };
    listen-on { any; };
    allow-transfer { 172.18.0.3; };   
    notify yes;
};

zone "jonas.lan" {
    type master;
    file "/etc/bind/db.jonas.lan";
    allow-transfer { 172.18.0.3; };
    also-notify { 172.18.0.3; };
};
